export const nationality: {
  name: string;
  code: string;
  iso?: string;
}[] = [
  { name: "アフガニスタン", code: "AFG", iso: "af" },
  { name: "アンギラ", code: "AIA", iso: "ai" },
  { name: "アルバニア", code: "ALB", iso: "al" },
  { name: "アルジェリア", code: "ALG", iso: "dz" },
  { name: "アンドラ", code: "AND", iso: "ad" },
  { name: "アンゴラ", code: "ANG" },
  { name: "オランダ領アンティル", code: "ANT" },
  { name: "アルゼンチン", code: "ARG", iso: "ar" },
  { name: "アルメニア", code: "ARM", iso: "am" },
  { name: "アルバ", code: "ARU" },
  { name: "アメリカ領サモア", code: "ASA" },
  { name: "アンティグア・バーブーダ", code: "ATG" },
  { name: "オーストラリア", code: "AUS", iso: "au" },
  { name: "オーストリア", code: "AUT", iso: "at" },
  { name: "アゼルバイジャン", code: "AZE", iso: "az" },
  { name: "バハマ", code: "BAH" },
  { name: "バングラデシュ", code: "BAN", iso: "bd" },
  { name: "ブルンジ", code: "BDI", iso: "by" },
  { name: "ベルギー", code: "BEL", iso: "be" },
  { name: "ベナン", code: "BEN" },
  { name: "バミューダ諸島", code: "BER" },
  { name: "ブルキナファソ", code: "BFA", iso: "bf" },
  { name: "バーレーン", code: "BHR" },
  { name: "ブータン", code: "BHU" },
  { name: "ボスニア・ヘルツェゴビナ", code: "BIH", iso: "ba" },
  { name: "ベラルーシ", code: "BLR" },
  { name: "ベリーズ", code: "BLZ" },
  { name: "ボリビア", code: "BOL", iso: "bo" },
  { name: "ボツワナ", code: "BOT" },
  { name: "ブラジル", code: "BRA", iso: "br" },
  { name: "バルバドス", code: "BRB" },
  { name: "ブルネイ", code: "BRU" },
  { name: "ブルガリア", code: "BUL", iso: "bg" },
  { name: "カンボジア", code: "CAM", iso: "kh" },
  { name: "カナダ", code: "CAN", iso: "ca" },
  { name: "ケイマン諸島", code: "CAY" },
  { name: "コンゴ共和国", code: "CGO" },
  { name: "チャド", code: "CHA" },
  { name: "チリ", code: "CHI", iso: "cl" },
  { name: "中国", code: "CHN", iso: "cn" },
  { name: "コートジボワール", code: "CIV", iso: "ci"  },
  { name: "カメルーン", code: "CMR" },
  { name: "コンゴ民主共和国", code: "COD" },
  { name: "クック諸島", code: "COK" },
  { name: "コロンビア", code: "COL", iso: "co" },
  { name: "コモロ", code: "COM" },
  { name: "カーボベルデ", code: "CPV", iso: "cv" },
  { name: "コスタリカ", code: "CRC", iso: "cr" },
  { name: "クロアチア", code: "CRO", iso: "hr" },
  { name: "中央アフリカ", code: "CTA" },
  { name: "キューバ", code: "CUB" },
  { name: "キュラソー", code: "CUW", iso: "cw" },
  { name: "キプロス", code: "CYP" },
  { name: "チェコ", code: "CZE", iso: "cz" },
  { name: "デンマーク", code: "DEN", iso: "dk" },
  { name: "ジブチ", code: "DJI" },
  { name: "ドミニカ国", code: "DMA" },
  { name: "ドミニカ共和国", code: "DOM" },
  { name: "エクアドル", code: "ECU", iso: "ec" },
  { name: "エジプト", code: "EGY", iso: "eg" },
  { name: "イングランド", code: "ENG", iso: "gb-eng" },
  { name: "赤道ギニア", code: "EQG" },
  { name: "エリトリア", code: "ERI" },
  { name: "スペイン", code: "ESP", iso: "es" },
  { name: "エストニア", code: "EST", iso: "ee" },
  { name: "エチオピア", code: "ETH" },
  { name: "フィジー", code: "FIJ" },
  { name: "フィンランド", code: "FIN", iso: "fi" },
  { name: "フランス", code: "FRA", iso: "fr" },
  { name: "フェロー諸島", code: "FRO" },
  { name: "ミクロネシア連邦", code: "FSM" },
  { name: "ガボン", code: "GAB", iso: "ga" },
  { name: "ガンビア", code: "GAM" },
  { name: "ジョージア", code: "GEO" },
  { name: "ドイツ", code: "GER", iso: "de" },
  { name: "ガーナ", code: "GHA" },
  { name: "ジブラルタル", code: "GIB" },
  { name: "ギニアビサウ", code: "GNB", iso: "gw" },
  { name: "グアドループ", code: "GPE" },
  { name: "ギリシャ", code: "GRE", iso: "gr" },
  { name: "グレナダ", code: "GRN" },
  { name: "グアテマラ", code: "GUA" },
  { name: "ギニア", code: "GUI" },
  { name: "グアム", code: "GUM" },
  { name: "ガイアナ", code: "GUY" },
  { name: "フランス領ギアナ", code: "GYF" },
  { name: "ハイチ", code: "HAI" },
  { name: "香港", code: "HKG", iso: "hk" },
  { name: "ホンジュラス", code: "HON" },
  { name: "ハンガリー", code: "HUN" },
  { name: "インドネシア", code: "IDN", iso: "id" },
  { name: "インド", code: "IND", iso: "in" },
  { name: "アイルランド", code: "IRL", iso: "ie" },
  { name: "イラン", code: "IRN", iso: "ir" },
  { name: "イラク", code: "IRQ", iso: "iq" },
  { name: "アイスランド", code: "ISL" },
  { name: "イスラエル", code: "ISR" },
  { name: "イタリア", code: "ITA" },
  { name: "ジャマイカ", code: "JAM" },
  { name: "ヨルダン", code: "JOR" },
  { name: "日本", code: "JPN", iso: "jp" },
  { name: "カザフスタン", code: "KAZ" },
  { name: "ケニア", code: "KEN", iso: "ke" },
  { name: "キルギス", code: "KGZ", iso: "kg" },
  { name: "韓国", code: "KOR", iso: "kr" },
  { name: "サウジアラビア", code: "KSA" },
  { name: "クウェート", code: "KUW" },
  { name: "コソボ", code: "KVX", iso: "xk" },
  { name: "ラオス", code: "LAO" },
  { name: "リベリア", code: "LBR" },
  { name: "リビア", code: "LBY" },
  { name: "セントルシア", code: "LCA" },
  { name: "レソト", code: "LES" },
  { name: "レバノン", code: "LIB", iso: "lb" },
  { name: "リヒテンシュタイン", code: "LIE" },
  { name: "リトアニア", code: "LTU", iso: "lt" },
  { name: "ルクセンブルク", code: "LUX" },
  { name: "ラトビア", code: "LVA", iso: "lv" },
  { name: "マカオ", code: "MAC" },
  { name: "マダガスカル", code: "MAD" },
  { name: "モロッコ", code: "MAR", iso: "ma" },
  { name: "マレーシア", code: "MAS", iso: "my" },
  { name: "モルドバ", code: "MDA" },
  { name: "モルディブ", code: "MDV" },
  { name: "メキシコ", code: "MEX", iso: "mx" },
  { name: "モンゴル", code: "MGL", iso: "mn" },
  { name: "北マケドニア", code: "MKD", iso: "mk" },
  { name: "マリ", code: "MLI" },
  { name: "マルタ", code: "MLT" },
  { name: "モンテネグロ", code: "MNE" },
  { name: "モザンビーク", code: "MOZ", iso: "mz" },
  { name: "モーリシャス", code: "MRI" },
  { name: "モントセラト", code: "MSR" },
  { name: "モーリタニア", code: "MTN" },
  { name: "マルティニーク", code: "MTQ" },
  { name: "マラウイ", code: "MWI", iso: "mw" },
  { name: "ミャンマー", code: "MYA" },
  { name: "ナミビア", code: "NAM" },
  { name: "ニカラグア", code: "NCA" },
  { name: "ニューカレドニア", code: "NCL" },
  { name: "オランダ", code: "NED", iso: "nl" },
  { name: "ネパール", code: "NEP" },
  { name: "ナイジェリア", code: "NGA", iso: "ng" },
  { name: "ニジェール", code: "NIG" },
  { name: "北アイルランド", code: "NIR" },
  { name: "ニウエ", code: "NIU" },
  { name: "北マリアナ諸島", code: "NMI" },
  { name: "ノルウェー", code: "NOR", iso: "no" },
  { name: "ニュージーランド", code: "NZL", iso: "nz" },
  { name: "オマーン", code: "OMA" },
  { name: "パキスタン", code: "PAK" },
  { name: "パナマ", code: "PAN" },
  { name: "パラグアイ", code: "PAR", iso: "py" },
  { name: "ペルー", code: "PER", iso: "pe" },
  { name: "フィリピン", code: "PHI", iso: "ph" },
  { name: "パレスチナ", code: "PLE" },
  { name: "パラオ", code: "PLW" },
  { name: "パプアニューギニア", code: "PNG" },
  { name: "ポーランド", code: "POL", iso: "pl" },
  { name: "ポルトガル", code: "POR", iso: "pt" },
  { name: "北朝鮮", code: "PRK", iso: "kp" },
  { name: "プエルトリコ", code: "PUR" },
  { name: "カタール", code: "QAT" },
  { name: "レユニオン", code: "REU" },
  { name: "ルーマニア", code: "ROU" },
  { name: "南アフリカ共和国", code: "RSA" },
  { name: "ロシア", code: "RUS", iso: "ru" },
  { name: "ルワンダ", code: "RWA" },
  { name: "サモア", code: "SAM" },
  { name: "スコットランド", code: "SCO", iso: "gb-sct" },
  { name: "セネガル", code: "SEN" },
  { name: "セーシェル", code: "SEY" },
  { name: "シンガポール", code: "SIN", iso: "sg" },
  { name: "セントクリストファー・ネイビス", code: "SKN" },
  { name: "シエラレオネ", code: "SLE" },
  { name: "エルサルバドル", code: "SLV" },
  { name: "サンマリノ", code: "SMR" },
  { name: "サン・マルタン3", code: "SMT" },
  { name: "ソロモン諸島", code: "SOL" },
  { name: "ソマリア", code: "SOM" },
  { name: "セルビア", code: "SRB", iso: "rs" },
  { name: "スリランカ", code: "SRI" },
  { name: "南スーダン", code: "SSD" },
  { name: "サントメ・プリンシペ", code: "STP" },
  { name: "スーダン", code: "SUD" },
  { name: "スイス", code: "SUI", iso: "ch" },
  { name: "スリナム", code: "SUR" },
  { name: "スロバキア", code: "SVK", iso: "sk" },
  { name: "スロベニア", code: "SVN", iso: "si" },
  { name: "スウェーデン", code: "SWE", iso: "se" },
  { name: "スワジランド", code: "SWZ" },
  { name: "シント・マールテン", code: "SXM" },
  { name: "シリア", code: "SYR" },
  { name: "タヒチ", code: "TAH" },
  { name: "タンザニア", code: "TAN" },
  { name: "タークス・カイコス諸島", code: "TCA" },
  { name: "トンガ", code: "TGA" },
  { name: "タイ", code: "THA", iso: "th" },
  { name: "タジキスタン", code: "TJK" },
  { name: "トルクメニスタン", code: "TKM" },
  { name: "東ティモール", code: "TLS" },
  { name: "トーゴ", code: "TOG" },
  { name: "チャイニーズタイペイ", code: "TPE", iso: "tw" },
  { name: "トリニダード・トバゴ", code: "TRI" },
  { name: "チュニジア", code: "TUN" },
  { name: "トルコ", code: "TUR", iso: "tr" },
  { name: "ツバル", code: "TUV" },
  { name: "アラブ首長国連邦", code: "UAE" },
  { name: "ウガンダ", code: "UGA" },
  { name: "ウクライナ", code: "UKR", iso: "ua" },
  { name: "ウルグアイ", code: "URU", iso: "uy" },
  { name: "アメリカ合衆国", code: "USA", iso: "us" },
  { name: "ウズベキスタン", code: "UZB", iso: "uz" },
  { name: "バヌアツ", code: "VAN" },
  { name: "ベネズエラ", code: "VEN", iso: "ve" },
  { name: "イギリス領ヴァージン諸島", code: "VGB" },
  { name: "ベトナム", code: "VIE" },
  { name: "セントビンセント・グレナディーン", code: "VIN" },
  { name: "アメリカ領ヴァージン諸島", code: "VIR" },
  { name: "ウェールズ", code: "WAL" },
  { name: "イエメン", code: "YEM" },
  { name: "ザンビア", code: "ZAM" },
  { name: "ザンジバル", code: "ZAN" },
  { name: "ジンバブエ", code: "ZIM" }
];
