name: deploy-github-actions

# When master branch updated, action will be carried on
on:
  push:
    branches:
      - master

# environment variables
env:
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
  FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
  GOOGLE_ANAYLTICS_ID: ${{ secrets.GOOGLE_ANAYLTICS_ID }}

# Jobs
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Install Dependencies
      run: npm ci
    - name: Test Build
      run: npm run deploy-hosting